# Homebrew formula for demodsl — generated by .github/workflows/publish.yml.
#
# Install with:  brew install Fran-cois/demodsl/demodsl
#
# This formula ships the standalone PyInstaller binaries attached to each
# GitHub Release rather than building a Python virtualenv from source.
# A source build would need a `resource` stanza for every transitive
# dependency (playwright, pydantic, typer, ...), regenerated on every
# release. The release binaries are already built and smoke-tested by CI,
# so this stays correct on its own.
#
# The __PLACEHOLDER__ values are substituted by CI from the real assets.

class Demodsl < Formula
  desc "DSL-driven automated product demo video generator"
  homepage "https://fran-cois.github.io/demodsl"
  version "3.9.0"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    on_arm do
      url "https://github.com/Fran-cois/demodsl/releases/download/v3.9.0/demodsl-3.9.0-macos-aarch64.tar.gz"
      sha256 "9ef1a9e966588220c201c7befa4fd2f9c058e672b46565e9b0ed8dc9d184fb07"
    end
    on_intel do
      url "https://github.com/Fran-cois/demodsl/releases/download/v3.9.0/demodsl-3.9.0-macos-x86_64.tar.gz"
      sha256 "cabd112e4556e6c4ee4791573ec91fbb4e6be7e1432f74cef31c71ad7363d87c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fran-cois/demodsl/releases/download/v3.9.0/demodsl-3.9.0-linux-x86_64.tar.gz"
      sha256 "d8b31bf97c8ba94c4d5e5acc293e3a5ab673fe97812187f2f7a595f5f612408a"
    end
  end

  def install
    bin.install "demodsl"
  end

  def caveats
    <<~EOS
      Rendering a demo drives a real browser, and the standalone binary does
      not ship Playwright's Chromium. Commands that never touch a browser
      (validate, capabilities, estimate, qa, eval) work as-is.

      To record a page, install the browser once:
        pipx run playwright install chromium

      ffmpeg is pulled in as a dependency and is used for the final encode.
    EOS
  end

  test do
    assert_match "Usage", shell_output("#{bin}/demodsl --help")
    assert_match version.to_s, shell_output("#{bin}/demodsl capabilities")
  end
end
