# Homebrew formula for demodsl — generated by .github/workflows/publish.yml.
#
# Install with:  brew install Fran-cois/demodsl/demodsl
#
# This formula ships the standalone PyInstaller binaries attached to each
# GitHub Release rather than building a Python virtualenv from source.
# A source build would need a `resource` stanza for every transitive
# dependency (playwright, pydantic, typer, ...), regenerated on every
# release. The release binaries are already built and smoke-tested by CI,
# so this stays correct on its own.
#
# The __PLACEHOLDER__ values are substituted by CI from the real assets.

class Demodsl < Formula
  desc "DSL-driven automated product demo video generator"
  homepage "https://fran-cois.github.io/demodsl"
  version "3.12.0"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    on_arm do
      url "https://github.com/Fran-cois/demodsl/releases/download/v3.12.0/demodsl-3.12.0-macos-aarch64.tar.gz"
      sha256 "d95acbafa6081608c74c26b61bf11c214e44747e11831f268354bbda352f5d3e"
    end
    on_intel do
      url "https://github.com/Fran-cois/demodsl/releases/download/v3.12.0/demodsl-3.12.0-macos-x86_64.tar.gz"
      sha256 "d46e325e7989214fd2ef99dccf02b2491a3cad75ce8ca557ce27b34a6e063151"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fran-cois/demodsl/releases/download/v3.12.0/demodsl-3.12.0-linux-x86_64.tar.gz"
      sha256 "5a0937eb0602d93fa01b8559932c35159eacd1d5b75549980024cb573e33cc98"
    end
  end

  def install
    bin.install "demodsl"
  end

  def caveats
    <<~EOS
      Rendering a demo drives a real browser, and the standalone binary does
      not ship Playwright's Chromium. Commands that never touch a browser
      (validate, capabilities, estimate, qa, eval) work as-is.

      To record a page, install the browser once:
        pipx run playwright install chromium

      ffmpeg is pulled in as a dependency and is used for the final encode.
    EOS
  end

  test do
    assert_match "Usage", shell_output("#{bin}/demodsl --help")
    assert_match version.to_s, shell_output("#{bin}/demodsl capabilities")
  end
end
